#!/bin/bash

if [[ "$OSTYPE" == "linux-gnu" ]]; then
  # Launch original ncmpcpp exec
  /usr/bin/ncmpcpp
elif [[ "$OSTYPE" == "darwin"* ]]; then
  # Set the name on the iTerm tab
  tabset --color turquoise
fi
