#!/bin/bash

if [[ "$OSTYPE" == "linux-gnu" ]]; then
  # Navigate to the default folder
  cd $HOME/Cloud/Home/Org
  # Launch original ranger exec
  /usr/bin/ranger
elif [[ "$OSTYPE" == "darwin"* ]]; then
  # Set the name on the iTerm tab
  tabset --color lightgreen --title "Ranger"
  # Launch original ranger exec
  /usr/local/bin/ranger
fi
