#!/bin/bash

  # TODO: Configure these values to be dependant on the machine used
  export monitor1="DP-1"
  export monitor2="HDMI-0"

  ###---Configuration---###
  export PS1="${debian_chroot:+($debian_chroot)}\[\033[00;36m\]⚈ \[\033[01;33m\]\W\[\033[00m\] " # Customize bash prompt
  [[ "$OSTYPE" == "linux-gnu" ]] && shopt -s autocd # Allows to cd into directory by typing it's name
  [[ "$OSTYPE" == "linux-gnu" ]] && alias ls="ls -hN --color=auto --group-directories-first" # Customize ls output
  alias grep="grep --color=auto" # Color grep - highlight desired sequence
  alias ccat="highlight --out-format=ansi" # Color cat - print file with syntax highlighting
	
###---Aliases---###

  # Set an alias for ncmpcpp, the acronym that I can never remember nor type in properly
  alias ncmpcpp=$HOME/.config/ncmpcpp/ncmpcpp
  alias ranger=$HOME/.config/ranger/ranger
  alias e=$EDITOR
  # Needed to simplify the process of copying STDOUT into system clipboard (e.g. ls | xclip)
  alias xclip='xclip -selection c'
  alias preview=/Users/sviat/.config/bin/preview
  alias setTerminalTabName=setTerminalTabName
  alias bfg="java -jar /Users/sviat/.config/utils/bfg.jar" # BFG Repo-Cleaner, removes large or troublesome blobs like git-filter-branch does, but faster.
  alias slack-term="node /Users/sviat/.config/slack-term/slack-term"
  alias archey3="archey3 --config $HOME/.config/archey3.cfg" # Output Arch Linux logo and system information
  alias dmenu="rofi -dmenu"
  alias wallpaper="feh --recursive --randomize --bg-scale $CLOUD/Home/Org/Home/Media/Wallpapers/*"
  alias connectToHome="sudo openvpn --config $CLOUD/Home/Org/Home/Software/Systems/Common/OpenVPN/vpn1.home.sviat.co.ovpn --pull-filter ignore redirect-gateway"


###---Functions---###
  ## Display docs of any format inside the terminal
  doc () {
    pandoc $1 | lynx -stdin
  }


export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
