#!/bin/sh

# Profile file. Runs on login.

export PATH="$PATH:$HOME/.config/bin"
export TERMINAL="urxvt"
export EDITOR="emacsclient -nw" # Default text editor      
export GPGKEY="E14771D03F56AF10" # Default public GPG key    
export CLOUD="/home/sviat/Cloud" # NextCloud directory path
export XDG_CONFIG_HOME=$HOME/.config # Dotconfig dir       
export hosts=/private/etc/hosts
export MPD_HOST=$HOME/.config/mpd/mpd.socket # MPD connection host
export MPD_PORT=6600 # MPD connection port
export APPMENU_DISPLAY_BOTH=1 # Show the menubar in apps that may otherwise hide it when the hud-menu-service is running
export QT_QPA_PLATFORMTHEME=appmenu-qt5 # After installing the appmenu-qt5 platform theme (to the qt5/plugins/platformthemes/ plugin directory) for the appmenu support to work you need to force Qt5 to use this platform theme plugin. This can be done by:

# Added bashrc file for interactive shell scripting
if [ -f ~/.bashrc ]; then . ~/.bashrc; fi

# Run XORG with tty1 on boot
[[ ! $DISPLAY && XDG_VTNR -eq 1 ]] && exec startx

# Necessary for HUD-menu to work
if [ -n "$GTK_MODULES" ]
  then GTK_MODULES="$GTK_MODULES:unity-gtk-module"
  else GTK_MODULES="unity-gtk-module"
fi

if [ -z "$UBUNTU_MENUPROXY" ]
  then UBUNTU_MENUPROXY=1
fi

###---Enable NVM---###
export NVM_DIR="$HOME/.nvm"
source /usr/share/nvm/nvm.sh
source /usr/share/nvm/bash_completion
source /usr/share/nvm/install-nvm-exec
###---End of Enable NVM---###
